[theme]
# Base theme: DARK.
base = "dark"

# Accent color (buttons, links, slider).
primaryColor = "#B71C1C"

# App background color. Dark shade.
backgroundColor = "#0E1117"

# Background color for sidebar and containers. Slightly lighter dark shade.
secondaryBackgroundColor = "#262730"

# Font color. White/light for readability on a dark background.
textColor = "#FAFAFA"

# Use a smaller font.
font = "sans serif"
